Added models, routers and controllers templates for author and book entity
yana-glt/library pull request #1
Opened 2023-12-06 14:46 UTC by yana-glt

Added models, routers and controllers templates for author and book entity.
Created db and configured connection to db

2023-12-06 16:35 UTC, FCosta20 commented on src/models/book.ts
> +        author:{type: mongoose.Schema.Types.ObjectId, required:true, ref:'Author'},
Why is book having an author but authors don't have a books property?

2023-12-06 16:37 UTC, FCosta20 commented on src/routers/indexRoute.ts
Why do we need this file?

2023-12-06 18:03 UTC, yana-glt commented on src/routers/indexRoute.ts
it will be the route for my home page where user will see the new books added to the library

2023-12-06 18:05 UTC, yana-glt commented on src/models/book.ts
> +        author:{type: mongoose.Schema.Types.ObjectId, required:true, ref:'Author'},
because I didn't use this property in the code. I haven't needed it yet, but I agree that it would be logical to add

2023-12-06 23:15 UTC, FCosta20 requested changes

2023-12-06 23:15 UTC, FCosta20 commented on src/server.ts
> +db.on('error', (err:string) => {console.log(err)});
I think it is a good practice to add a process exit after logging an error of the db connection.

Also didn't you consider using try catch and await for the connection instead of db.on?

2023-12-07 00:39 UTC, yana-glt commented on src/server.ts
> +db.on('error', (err:string) => {console.log(err)});
I tried to add it in a new commit

2023-12-07 03:25 UTC, FCosta20 approved these changes

2023-12-07 03:25 UTC, merged